#!/usr/bin/env tclsh
## -*- tcl -*-
# # ## ### ##### ######## ############# ######################

# @@ Meta Begin
# Application cm   ?
# Meta author      {Andreas Kupries}
# Meta category    ?
# Meta description ?
# Meta location    http:/core.tcl.tk/akupries/cm
# Meta platform    tcl
# Meta require     cm
# Meta require     {Tcl 8.5-}
# Meta subject     ?
# Meta summary     ?
# @@ Meta End

package require Tcl 8.5
package require debug
package require debug::caller
package require cmdr::color

debug header {[::cmdr color {black bg-cyan} [clock format [clock seconds]]] }

package require cm
package require cm::validate::colormode
package require cm::validate::debug
#package require cm::atexit

# # ## ### ##### ######## ############# ######################
## Process a few flags early (color mode, debug narrative)
## Note: color mode before debug flags so that debug output
##       can be colorized immediately.

cm validate colormode process-early $argv
cm validate debug     process-early $argv

# # ## ### ##### ######## ############# ######################
## Invoke the application code.
## Should possibly catch signals as well.

set status 1
try {
    set status [cm main $argv]
} finally {
    exit $status
}

# # ## ### ##### ######## ############# ######################
exit
