#!/bin/sh

if test "X$1" = "X"
then
    echo 1>&2 usage: $0 test-file
    exit 1
fi

tests="$1"
tests="$(basename "$tests")"

ftilde
rtilde
sleep 2
clear
echo
rm -f X.*

mkdir tbak
mv tests/*.test tbak/
mv tbak/$tests tests/ 

./build.tcl test --log X
echo
echo tested = $(date)
echo

mv tbak/* tests/
rmdir tbak
